--TRIGGER
GO
CREATE TRIGGER TRG_BILL_PATIENT_BALANCE
ON BILL
AFTER INSERT
AS
DECLARE @ERRORMESSAGE VARCHAR(200) = 'Tigger error';
BEGIN
BEGIN TRY
IF EXISTS(SELECT 1 FROM INSERTED WHERE B_TOTAL_AMOUNT IS NULL OR B_TOTAL_AMOUNT <= 0)
   BEGIN
    SET @ERRORMESSAGE = 'Bill amount cannot be null or negative or 0'
    RAISERROR(@ERRORMESSAGE, 16,1)
    ROLLBACK TRANSACTION;
   END
ELSE IF NOT EXISTS(SELECT 1 FROM PATIENT P JOIN APPOINTMENT A ON P.P_ID = A.P_ID
									       JOIN VISIT V ON A.AP_ID = V.AP_ID
									       JOIN INSERTED I ON I.V_ID = V.V_ID)                  
   BEGIN
    SET @ERRORMESSAGE = 'Patient does not exist.'
    RAISERROR(@ERRORMESSAGE, 16,1)
    ROLLBACK TRANSACTION;
   END;
ELSE 
   BEGIN
   UPDATE P 
   SET P.PAT_BALANCE = P.PAT_BALANCE + I.B_TOTAL_AMOUNT
   FROM PATIENT P JOIN APPOINTMENT A ON P.P_ID = A.P_ID JOIN VISIT V ON A.AP_ID = V.AP_ID
									  JOIN INSERTED I ON I.V_ID = V.V_ID;
   END;
END TRY
BEGIN CATCH
 RAISERROR(@ERRORMESSAGE, 16,1)
 ROLLBACK TRANSACTION 
END CATCH;

END;
GO
--The trigger gets executed and raises and error saying the bill is less than 0. So, we have to rollback appointment and visit as well since the appointment must have a visit and a bill must have a bill.
BEGIN TRANSACTION
INSERT INTO APPOINTMENT
VALUES ('78901', '101', '1006', '2026-04-28', '8:00', 'Cleaning', 'SCHEDULED');
INSERT INTO VISIT
VALUES ('117', '2026-04-28', 'Very white.', '00011', '78901');
INSERT INTO BILL VALUES('207', '2026-04-28', -50, 'UNPAID', '117');
COMMIT TRANSACTION

--The trigger never gets executed because the P_ID is in Appointment and not Bill
BEGIN TRANSACTION
INSERT INTO APPOINTMENT
VALUES ('78901', '101', '0000', '2026-04-28', '8:00', 'Cleaning', 'SCHEDULED');
INSERT INTO VISIT
VALUES ('117', '2026-04-28', 'Very white.', '00011', '78901');
INSERT INTO BILL VALUES('207', '2026-04-28', 100, 'UNPAID', '117');
COMMIT TRANSACTION

--Patient balance went from 1200.00 to 1355.00
BEGIN TRANSACTION
INSERT INTO APPOINTMENT
VALUES ('78901', '101', '1006', '2026-04-28', '8:00', 'Cleaning', 'SCHEDULED');
INSERT INTO VISIT
VALUES ('117', '2026-04-28', 'Very white.', '00011', '78901');
INSERT INTO BILL VALUES('207', '2026-04-28', 155.00, 'UNPAID', '117');
COMMIT TRANSACTION

--FUNCTION AND STORED PROCEDURE
GO
CREATE FUNCTION FUNC_REMAINNING_BALANCE (@B_ID CHAR(5))
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @REMAININGBALANCE DECIMAL(10,2), @TOTAL DECIMAL(10,2), @PAID DECIMAL(10,2)

    --GET THE BILL
    SELECT @TOTAL = B_TOTAL_AMOUNT FROM BILL WHERE B_ID = @B_ID;
    --GET THE PAYMENT
     SELECT @PAID = SUM(PAY_AMOUNT) FROM PAYMENT WHERE B_ID = @B_ID;
     IF(@PAID IS NULL) 
        BEGIN
        SET @PAID = 0;
        END;
     SET @REMAININGBALANCE = @TOTAL-@PAID;
     RETURN @REMAININGBALANCE;
END;
GO

SELECT DBO.FUNC_REMAINNING_BALANCE('203') AS 'Remaining Balance'

GO
CREATE PROCEDURE PRC_ADD_PAYMENT @B_ID CHAR(5), @P_ID CHAR(5), @PAY_AMOUNT DECIMAL(10,2), @PAY_METHOD VARCHAR(300)
AS
BEGIN
 BEGIN TRY
   IF @PAY_AMOUNT<= 0
       BEGIN
          RAISERROR('Amount cannot be 0 or less', 16,1);
       END;
   ELSE IF NOT EXISTS (SELECT 1 FROM PATIENT WHERE P_ID = @P_ID)
       BEGIN
          RAISERROR('Patient does not exist', 16,1)
       END;
   ELSE IF NOT EXISTS (SELECT 1 FROM BILL B JOIN VISIT V ON B.V_ID = V.V_ID JOIN APPOINTMENT A ON A.AP_ID = V.AP_ID JOIN PATIENT P ON A.P_ID = P.P_ID WHERE B.B_ID = @B_ID)
       BEGIN
          RAISERROR('Bill does not exist', 16,1)
       END;
   ELSE IF @PAY_METHOD NOT IN ('CASH', 'CARD', 'INSURANCE')
       BEGIN
       RAISERROR ('Pay method must be CASH, CARD OR INSURANCE', 16, 1)
       END;
   ELSE 
       BEGIN
          INSERT INTO PAYMENT(PAY_ID,PAY_Date, PAY_Method,PAY_Amount, P_ID, B_ID) 
          VALUES(NEXT VALUE FOR SEQ_PAYMENT, GETDATE(), @PAY_METHOD, @PAY_AMOUNT, @P_ID, @B_ID); 
          DECLARE @REMAINING DECIMAL(10,2)
          SET @REMAINING = DBO.FUNC_REMAINNING_BALANCE(@B_ID)
          IF @REMAINING <= 0
             BEGIN
                UPDATE BILL
                SET B_PAID_STATUS = 'PAID'
                WHERE B_ID = @B_ID;
             END;
          ELSE IF @REMAINING < (SELECT B_TOTAL_AMOUNT FROM BILL WHERE B_ID = @B_ID)
             BEGIN
                UPDATE BILL
                SET B_PAID_STATUS = 'PARTIAL'
                WHERE B_ID = @B_ID;
             END;
       END;
  END TRY
  BEGIN CATCH
      THROW;
  END CATCH;
END;
GO
--Pay amount must be more than 0
EXEC PRC_ADD_PAYMENT '203', '1003',-98, 'CARD' 
--Patient does not exist
EXEC PRC_ADD_PAYMENT '203', '1903',100.00, 'CARD' 
--Bill ID does not exist
EXEC PRC_ADD_PAYMENT '2903', '1003',100.00, 'CARD' 
--Pay method does not respect the check constraint
EXEC PRC_ADD_PAYMENT '203', '1003',100.00, 'HELLO' 
--Works well
EXEC PRC_ADD_PAYMENT '203', '1003',100.00, 'INSURANCE' 

--COMPLEX QUERY

SELECT P.P_ID, P.P_Fname, P.P_Lname, SUM(B.B_Total_Amount) AS Total_Billed, SUM(COALESCE(PA.Total_Paid,0)) AS Total_Paid, (SUM(B.B_Total_Amount) - SUM(COALESCE(PA.Total_Paid,0))) AS Remaining_Balance
FROM PATIENT P JOIN APPOINTMENT A
ON P.P_ID = A.P_ID
JOIN VISIT V 
ON A.AP_ID = V.AP_ID
JOIN BILL B
ON B.V_ID = V.V_ID
LEFT JOIN (SELECT B_ID, SUM(PAY_Amount) AS Total_Paid
            FROM PAYMENT
            GROUP BY B_ID) PA
ON PA.B_ID = B.B_ID
GROUP BY P.P_ID, P.P_Fname, P.P_Lname
ORDER BY Remaining_Balance DESC;
--VIEW
GO
CREATE VIEW VW_INSURANCE_PATIENT_CLAIM_ACTIVITY AS
SELECT IC.INS_ID,  IC.Company_Name, CONCAT(P.P_Fname, ' ', P.P_Lname) AS Patient_Name, SUM(B.B_Total_Amount) AS Total_Billed, SUM(COALESCE(PA.Insurance_Amount,0)) AS Insurance_Covered
FROM INSURANCE_COMPANY IC JOIN PATIENT P 
ON IC.INS_ID = P.INS_ID
JOIN APPOINTMENT A
ON P.P_ID = A.P_ID
JOIN VISIT V 
ON A.AP_ID = V.AP_ID
JOIN BILL B
ON B.V_ID = V.V_ID
LEFT JOIN (SELECT B_ID, SUM(PAY_Amount) AS Insurance_Amount
            FROM PAYMENT
            WHERE PAY_Method = 'INSURANCE'
            GROUP BY B_ID) PA
ON PA.B_ID = B.B_ID
GROUP BY IC.INS_ID,  IC.Company_Name, P.P_Fname, P.P_Lname;
GO
SELECT * FROM DBO.VW_INSURANCE_PATIENT_CLAIM_ACTIVITY;

--VIEW
CREATE VIEW PATIENT_INFORMATION AS
SELECT P.P_ID, CONCAT(P_FNAME, ' ',
P_LNAME) AS 'Patient Name',
A.AP_DATE AS 'Appointment Date', 
A.AP_TIME AS 'Appoinment Time',
T.T_ID AS 'Treatment',
REASON  AS 'Reason',
CONCAT('Dr. ', D_FNAME, ' ' , D_LNAME) AS 'Dentist'

FROM PATIENT P JOIN APPOINTMENT A 
ON P.P_ID = A.P_ID
JOIN DENTIST D
ON A.D_ID = D.D_ID
JOIN VISIT V
ON V.AP_ID = A.AP_ID
JOIN TREATMENT T 
ON T.T_ID = V.T_ID;

SELECT * FROM PATIENT_INFORMATION

--function procedure
CREATE FUNCTION ANNUAL_PATIENTS (@DENTIST_ID CHAR(3)) 
RETURNS INT 
AS
BEGIN 
DECLARE @NUM_PATIENTS INT; 
	IF NOT EXISTS (SELECT 1 FROM DENTIST WHERE D_ID = @DENTIST_ID) 
		RETURN 0; 
	ELSE 
		BEGIN 
			SET @NUM_PATIENTS = (SELECT COUNT(P_ID) FROM APPOINTMENT WHERE D_ID = @DENTIST_ID AND YEAR(AP_DATE) = YEAR(GETDATE())); 
		END 
	RETURN @NUM_PATIENTS; 
END; 
--procedure
CREATE PROCEDURE DENTIST_ANNUAL_SALARY (@DENTIST_ID CHAR(3)) 
AS 
BEGIN 
BEGIN TRY 
DECLARE @COMMISSION NUMERIC (5,2),@PAY MONEY, @NUM_PATIENTS INT; 
IF NOT EXISTS (SELECT 1 FROM DENTIST WHERE D_ID = @DENTIST_ID) 
	PRINT 'This dentist does not exist.' 
ELSE IF NOT EXISTS (SELECT 1 FROM APPOINTMENT WHERE D_ID = @DENTIST_ID AND YEAR(AP_DATE) = YEAR(GETDATE())) 
	BEGIN
		SET @PAY = 0; 
		PRINT 'The dentist ' + @DENTIST_ID + ' did not see any patients this year.' 
	END 
ELSE 
	BEGIN 
		SELECT @PAY = (SELECT SUM(T_COST)  
		FROM TREATMENT T JOIN VISIT V 
		ON T.T_ID = V.T_ID 
		JOIN APPOINTMENT A 
		ON A.AP_ID = V.AP_ID 
		WHERE A.D_ID = @DENTIST_ID AND YEAR(A.AP_DATE) = YEAR(GETDATE()));
		SELECT @NUM_PATIENTS = DBO.ANNUAL_PATIENTS(@DENTIST_ID); 
		SELECT @COMMISSION = CASE 
			WHEN @NUM_PATIENTS < 2 THEN 0 
			ELSE 0.15 
			END; 
		SET @PAY = @PAY + (@COMMISSION*@PAY); 
		PRINT 'The dentist ' + @DENTIST_ID + ' has an annual pay of $' + CAST(@PAY AS VARCHAR(7)) + '.'; 
	END 
END TRY 
BEGIN CATCH 
THROW 
END CATCH 
END; 

EXEC DENTIST_ANNUAL_SALARY 101
EXEC DENTIST_ANNUAL_SALARY 776

SELECT DBO.ANNUAL_PATIENTS (101) AS 'Number of Patients'
SELECT DBO.ANNUAL_PATIENTS (726) AS 'Number of Patients'

--COMPLEX QUERIES
--1
SELECT T.T_NAME AS 'Treatment', COUNT(V.V_ID) AS 'Times Performed', SUM(B.B_TOTAL_AMOUNT) AS 'Total Revenue'
FROM TREATMENT T JOIN VISIT V
ON T.T_ID = V.T_ID
JOIN BILL B
ON B.V_ID = V.V_ID
GROUP BY T_NAME
ORDER BY 'Total Revenue' DESC;

--2
SELECT D.D_ID AS 'DentistID', D.D_FNAME AS 'First Name',  D.D_LNAME AS 'Last Name', COUNT(A.AP_ID) AS 'Total Appointments'
FROM DENTIST D JOIN APPOINTMENT A
ON D.D_ID = A.D_ID
GROUP BY D.D_ID, D.D_FNAME, D.D_LNAME
ORDER BY 'Total Appointments';


SELECT * FROM DENTIST;
SELECT * FROM PATIENT;
SELECT * FROM TREATMENT;
SELECT * FROM VISIT;
SELECT * FROM APPOINTMENT;
SELECT * FROM BILL;


 