SELECT * FROM INSURANCE_COMPANY;
SELECT * FROM PATIENT;
SELECT * FROM DENTIST;
SELECT * FROM APPOINTMENT;
SELECT * FROM TREATMENT;
SELECT * FROM VISIT;
SELECT * FROM BILL;
SELECT * FROM PAYMENT;
SELECT * FROM PAY;

--VIEW 1--Rend

CREATE VIEW PATIENT_INFORMATION AS
SELECT P.P_ID, CONCAT(P_FNAME, ' ',
P_LNAME) AS 'Patient Name',
A.AP_DATE AS 'Appointment Date', 
A.AP_TIME AS 'Appoinment Time',
T.T_ID AS 'Treatment',
REASON  AS 'Reason',
CONCAT('Dr. ', D_FNAME, ' ' , D_LNAME) AS 'Dentist'

FROM PATIENT P JOIN APPOINTMENT A 
ON P.P_ID = A.P_ID
JOIN DENTIST D
ON A.D_ID = D.D_ID
JOIN VISIT V
ON V.AP_ID = A.AP_ID
JOIN TREATMENT T 
ON T.T_ID = V.T_ID;

SELECT * FROM PATIENT_INFORMATION;


--COMPLEX QUERY 1 --REND